version: '3'
services:
    database:
        image: postgres
        container_name: kvc_database
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=kvc
        ports:
            - "5432:5432"
        restart: always